query GetEvents {
  getEvents {
    id
    roomId
    userCreated
    description
    finalTime
    initialTime
    ramalNumber
    totalPeople
    userRegistration
    email
    support {
      computer
      projector
      coffee
      water
    }
  }
}