query Event {
  event {
    id
    roomId
    userCreated
    description
    finalTime
    initialTime
    ramal_number
    total_people
    user_registration
    email
    support {
      computer
      projector
      coffee
      water
    }
  }
}
