query Event {
  event {
    id
    roomId
    room {
      name
    }
    userCreated
    description
    finalTime
    initialTime
    ramalNumber
    totalPeople
    userRegistration
    email
    support {
      computer
      projector
      coffee
      water
    }
  }
}
