// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AntDesignTextBox: typeof import("./components/controls/AntDesignTextBox.vue")["default"];
    DeleteButton: typeof import("./components/buttons/DeleteButton.vue")["default"];
    DropDown: typeof import("./components/buttons/DropDown.vue")["default"];
    FabButton: typeof import("./components/buttons/FabButton.vue")["default"];
    Gestao: typeof import("./components/gestao/index.vue")["default"];
    GestaoList: typeof import("./components/SistemaGestao/GestaoList.vue")["default"];
    HeaderBar: typeof import("./components/NavBar/HeaderBar.vue")["default"];
    HomeBanner: typeof import("./components/MainLayout/HomeBanner.vue")["default"];
    HomeCard: typeof import("./components/HomeCard.vue")["default"];
    LoaderButton: typeof import("./components/buttons/LoaderButton.vue")["default"];
    MainLayout: typeof import("./components/MainLayout/index.vue")["default"];
    NavBar: typeof import("./components/NavBar/index.vue")["default"];
    OptionLocales: typeof import("./components/OptionLocales.vue")["default"];
    Outros: typeof import("./components/Outros/index.vue")["default"];
    OutrosCard: typeof import("./components/Outros/OutrosCard.vue")["default"];
    PaymentButton: typeof import("./components/buttons/PaymentButton.vue")["default"];
    RhList: typeof import("./components/SistemaRh/RhList.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SendButton: typeof import("./components/buttons/SendButton.vue")["default"];
    SistemaGestao: typeof import("./components/SistemaGestao/index.vue")["default"];
    SistemaRh: typeof import("./components/SistemaRh/index.vue")["default"];
    Switches: typeof import("./components/switches/index.vue")["default"];
    SwitchRouded: typeof import("./components/switches/SwitchRouded.vue")["default"];
    TabHeader: typeof import("./components/TabHeader.vue")["default"];
    ThemeButton: typeof import("./components/buttons/ThemeButton.vue")["default"];
    ToggleTheme: typeof import("./components/ToggleTheme.vue")["default"];
    TranslationComponent: typeof import("./components/TranslationComponent.vue")["default"];
  }
}
