name: image build

on:
  push:
    tags:
      - "*"

jobs:
  image-build:
    runs-on:
      labels: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup registry credentials
        run: |
          echo //npm.pkg.github.com/:_authToken=${{ secrets.PACKAGE_TOKEN }} >> .npmrc
          yarn config set 'npmRegistries["//npm.pkg.github.com"].npmAuthToken' "${{ secrets.PACKAGE_TOKEN }}" --home

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: ghcr.io/${{ github.repository }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=latest
            type=raw,prefix=build-,value=${{ github.run_number }}
            type=schedule
            type=ref,event=branch,suffix=-${{github.run_number}}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read package.json
        uses: nyaa8/package-version@v1
        id: package-json-endpoint

      - name: Echo env vars
        run: |
          echo APP_VERSION=${{ env.PACKAGE_VERSION }}
          echo BUILD_NUMBER=${{ github.run_number }}
          echo GIT_HASH=${{ github.sha }}
          echo BUILDER=${{ github.actor }}
          echo BUILD_DATE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
          echo APP_REVISION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          secret-files: |
            "YARNRC=/home/runner/.yarnrc.yml"
          build-args: |
            MODE=production
            APP_VERSION=${{ env.PACKAGE_VERSION }}
            BUILD_NUMBER=${{ github.run_number }}
            GIT_HASH=${{ github.sha }}
            BUILDER=${{ github.actor }}
            BUILD_DATE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            APP_REVISION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:latest
          cache-to: type=inline
